language: python
python:
- '3.7'
install:
- pip install .
- pip install pytest coverage codecov flake8
- pip list
script:
- flake8 --exclude=tests/* --ignore=E501
- coverage run -m pytest -s
- codecov
