name: func-adl.xAOD-dev
channels:
  - conda-forge
  - defaults

dependencies:
  - flake8
  - python>=3.7.0
  - pip
  - pytest
  - pytest-asyncio
  - pip:
    - git+https://github.com/iris-hep/ast-language.git@e6470deb68529e1885a4bc46f781e2fe43a6f4c8
